### PR TITLE
LPS-62805 - Portal proxy doesn't work in 7.0, HTTP 404 for CSS and JS resources

### PR DESCRIPTION
**Pull request by mjbradford89**
Hey @topolik 

Hopefully no compilation errors this time :smile: 

Please let me know if there are any issues.

Thanks!

### CODE REVIEW

**Comment by mjbradford89** [comment]
I don't think these failures are related to my changes.

**Comment by topolik** [comment]
Pull request submitted at: https://github.com/jbalsas/liferay-portal/pull/452
View total diff: https://github.com/topolik/liferay-portal/compare/cfe872bc7e...5bf5e6f9a9

**Comment by topolik** [comment]
Thanks! 

We continue together with Chema to review it.
